### ISSUE TITLE
解压密码是多少

### ISSUE THREAD

**Issue by luoyedao** [junneyang/easy-ansible#1]
解压密码是多少

**Comment by junneyang** [comment]
这个源码不打算开放，欢迎交流，-^^-

**Comment by luoyedao** [comment]
嚓，我打算用ansible写个运维管理平台，就想借鉴你这个。你源码都不开发，咋交流啊？

**Comment by junneyang** [comment]
@luoyedao 
看了界面截图之后就知道有哪些核心功能了，怎么设计、实现可以交流。源码不开放。

**Comment by luoyedao** [comment]
好的，等我把大概框架弄好。有问题再请教您啊，往多多指教，我是菜鸟

**Comment by junneyang** [comment]
@luoyedao   好,  没问题
